version: "3.7"
services:
  api_service:
    build: .
    restart: always
    stdin_open: true
    tty: true      
    ports:
      - 8080:8080
    environment:
    - JVM_OPTS=-Xms3G -Xmx3G
    depends_on:
      - mongodb
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27017:27017
    restart: unless-stopped